trigger:
- main

pool:
  vmImage: ubuntu-latest

# free tier can't have parallelism
#strategy:
#  matrix:
#    python310:
#      python.version: '3.10'
#    python311:
#      python.version: '3.11'
#    python312:
#      python.version: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: 'Use Python 3.12'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Depedencies'

- script: |
    pytest tests/ --cov=src --cov-report=xml
  displayName: "Run Unit Tests"

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(build.BuildId)-3.12.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

